language: node_js
node_js:
  - "node"
script:
  - yarn run test
  - yarn run lint
  - yarn run coverage:generate
  - yarn run coverage:publish
branches:
  only:
    - master
    - dev
cache:
  yarn: true
